


INSERT INTO Funny (Quote)
VALUES
(' 1 in 5 people in the world are Chinese. There are 5 people in my family, so it must be one of them. It’s either my mum or my dad. Or my older brother Colin.'),
(' 100,000 sperm and you were the fastest?'),
(' 668 – The neighbour of the beast.'),
(' A bank is a place that will lend you money, if you can prove that you don’t need it.'),
(' A bargain is something you don’t need at a price you can’t resist.'),
(' A bus is a vehicle that runs twice as fast when you are after it as when you are in it.'),
(' A bus station is where a bus stops. A train station is where a train stops. On my desk, I have a work station.'),
(' A cat, by any other name, is still a sneaky little furball that barfs on the furniture.'),
(' A celebrity is someone who works hard all his life to become known and then wears dark glasses to avoid being recognized.'),
(' A cheap shot is a terrible thing to waste.'),
(' A clear conscience is usually the sign of a bad memory.'),
(' A committee is twelve men doing the work of one.'),
(' A computer once beat me at chess, but it was no match for me at kick boxing.'),
(' A conscience is what hurts when all your other parts feel so good.'),
(' A diplomat is someone who can tell you to go to hell in such a way that you will look forward to the trip.'),
(' A fine is a tax for doing wrong. A tax is a fine for doing well.'),
(' A friend is someone who will help you move. A GOOD friend is someone who will help you move a dead body.'),
(' A hard thing about a business is minding your own.'),
(' A little boy asked his father, “Daddy, how much does it cost to get married?” Father replied, “I don’t know son, I’m still paying.”.'),
(' A positive attitude may not solve all your problems, but it will annoy enough people to make it worth the effort.'),
(' A TV can insult your intelligence, but nothing rubs it in like a computer.'),
(' A woman has got to love a bad man once or twice in her life, to be thankful for a good one.'),
(' Accept it. Your parents HAVE had sex before.'),
(' According to a new survey, women say they feel more comfortable undressing in front of men than they do undressing in front of other women. They say that women are too judgmental, where, of course, men are just grateful.'),
(' Alcohol is a perfect solvent: It dissolves marriages, families and careers.'),
(' Alcoholism is the only disease that tries to convince you that you don’t have it.'),
(' Always borrow money from a pessimist. He won’t expect it back.'),
(' America is a country which produces citizens who will cross the ocean to fight for democracy but won’t cross the street to vote.'),
(' Anyone who has never made a mistake has never tried anything new.'),
(' Archeologist: someone whose carreer lies in ruins.'),
(' Artificial intelligence is no match for natural stupidity.'),
(' At every party there are two kinds of people: those who want to go home and those who don’t. The trouble is, they are usually married to each other.'),
(' Be careful of your thoughts, they may become words at any moment.'),
(' Be safety conscious. 80% of people are caused by accidents.'),
(' Beauty is only skin deep…but ugly goes all the way to the bone!.'),
(' Behind every successful man is his woman. Behind the fall of a successful man is usually another woman.'),
(' Being in a nudist colony probably takes all the fun out of Halloween.'),
(' Better to remain silent and be thought a fool, than to speak and remove all doubt.'),
(' Bills travel through the mail at twice the speed.'),
(' Build a man a fire, and he’ll be warm for a day. Set a man on fire, and he’ll be warm for the rest of his life.'),
(' By the time a man realises that his father was right, he has a son who thinks he’s wrong.'),
(' By the time you learn the rules of life, you’re too old to play the game.'),
(' Canadians are more polite when they are being rude than Americans are when they are being friendly.'),
(' Change is inevitable, except from a vending machine.'),
(' Children in the back seats of cars cause accidents, but accidents in the back seats of cars cause children.'),
(' Children in the dark make accidents, but accidents in the dark make children.'),
(' Children seldom misquote you. In fact, they usually repeat word for word what you shouldn’t have said.'),
(' Children: You spend the first 2 years of their life teaching them to walk and talk. Then you spend the next 16 years telling them to sit down and shut-up.'),
(' Clinton lied. A man might forget where he parks or where he lives, but he never forgets oral sex, no matter how bad it is.'),
(' Constipated people don’t give a crap.'),
(' Crowded elevators smell different to midgets.'),
(' Deja Vu – When you think you’re doing something you’ve done before, it’s because God thought it was so funny, he had to rewind it for his friends.'),
(' Did you hear about the guy whose whole left side was cut off? He’s all right now.'),
(' Did you know that dolphins are so smart that within a few weeks of captivity, they can train people to stand on the very edge of the pool and throw them fish?'),
(' Discretion is being able to raise your eyebrow instead of your voice.'),
(' Do not argue with an idiot. He will drag you down to his level and beat you with experience.'),
(' Do not walk behind me, for I may not lead. Do not walk ahead of me, for I may not follow. Do not walk beside me either. Just pretty much leave me the hell alone.'),
(' Do you realize that in about 40 years, we’ll have thousands of old ladies running around with tattoos?'),
(' Does this rag smell like chloroform to you?'),
(' Does time fly when you’re having sex or was it really just one minute?'),
(' Does time fly when you’re having sex or was it really just one minute?'),
(' Dogs have masters. Cats have staff.'),
(' Don’t hate me because I’m beautiful. Hate me because your boyfriend thinks so.'),
(' Don’t piss me off! I’m running out of places to hide the bodies.'),
(' Don’t steal. That’s the government’s job.'),
(' Drink coffee! Do stupid things faster with more energy!.'),
(' During sex, my girlfriend always wants to talk to me. Just the other night she called me from a hotel.'),
(' Efficiency is a highly developed form of laziness.'),
(' Evening news is where they begin with ‘Good evening’, and then proceed to tell you why it isn’t.'),
(' Ever notice that people who spend money on beer, cigarettes, and lottery tickets are always complaining about being broke and not feeling well?'),
(' Every day, man is making bigger and better fool-proof things, and every day, nature is making bigger and better fools. So far, I think nature is winning.'),
(' Every so often, I like to go to the window, look up, and smile for a satellite picture.'),
(' Everybody is somebody else’s weirdo.'),
(' Everyone has the right to be stupid, but you are abusing the privilege!.'),
(' Everything is edible, some things are only edible once.'),
(' Experience is what you get when you didn’t get what you wanted.'),
(' Failure is not falling down, it is not getting up again.'),
(' Fighting for peace is like fucking for virginity.'),
(' For every action, there is a corresponding over-reaction.'),
(' Foreign Aid: The transfer of money from poor people in rich countries to rich people in poor countries.'),
(' Friends are like condoms: They protect you when things get hard.'),
(' Friends may come and go, but enemies accumulate.'),
(' George Washington said “We would have a black president when pigs fly!”… well, swine flu.'),
(' Girls are like roads, more the curves, more the dangerous they are.'),
(' God must love stupid people. He made SO many.'),
(' Going to church doesn’t make you a Christian any more than standing in a garage makes you a car.'),
(' Good girls are bad girls that never get caught.'),
(' Good health is merely the slowest possible rate at which one can die.'),
(' Haikus are easy. But sometimes they don’t make sense. Refrigerator.'),
(' Hallmark Card: “I’m so miserable without you, it’s almost like you’re still here.”.'),
(' Ham and Eggs: A day’s work for a chicken, a lifetime commitment for a pig.'),
(' Hard work never killed anyone, but why take the chance?'),
(' Having sex is like playing bridge. If you don’t have a good partner, you’d better have a good hand.'),
(' He who smiles in a crisis has found someone to blame.'),
(' Hippopotomonstrosesquippedaliophobia: Fear of long words.'),
(' Hospitality: making your guests feel like they’re at home, even if you wish they were.'),
(' How do you get a sweet little 80-year-old lady to say the F word? Get another sweet little 80-year-old lady to yell *BINGO*!.'),
(' How do you get holy water? Boil the hell out of it.'),
(' How is it one careless match can start a forest fire, but it takes a whole box to start a campfire?'),
(' I always take life with a grain of salt, …plus a slice of lemon, …and a shot of tequila.'),
(' I am not a vegetarian because I love animals. I am a vegetarian because I hate plants.'),
(' I asked God for a bike, but I know God doesn’t work that way. So I stole a bike and asked for forgiveness.'),
(' I bet you I could stop gambling.'),
(' I didn’t fight my way to the top of the food chain to be a vegetarian.'),
(' I didn’t say it was your fault, I said I was blaming you.'),
(' I discovered I scream the same way whether I’m about to be devoured by a great white shark or if a piece of seaweed touches my foot.'),
(' I don’t have a beer gut, I have a protective covering for my rock hard abs.'),
(' I don’t have a solution, but I do admire the problem.'),
(' I don’t have an attitude problem. You have a perception problem.'),
(' I don’t have an attitude; I have a personality you can’t handle.'),
(' I don’t suffer from insanity. I enjoy every minute of it.'),
(' I don’t trust anything that bleeds for five days and doesn’t die.'),
(' I got in a fight one time with a really big guy, and he said, “I’m going to mop the floor with your face.” I said, “You’ll be sorry.” He said, “Oh, yeah? Why?” I said, “Well, you won’t be able to get into the corners very well.”.'),
(' I have all the money I’ll ever need – if I die by 4:00 p.m. today.'),
(' I have never understood why women love cats. Cats are independent, they don’t listen, they don’t come in when you call, they like to stay out all night, and when they’re home they like to be left alone and sleep. In other words, every quality that women hate in a man, they love in a cat.'),
(' I have to exercise early in the morning before my brain figures out what I’m doing.'),
(' I intend to live forever. So far, so good.'),
(' I like long walks, especially when they are taken by people who annoy me.'),
(' I like work. It fascinates me. I sit and look at it for hours.'),
(' I love oral sex…it’s the phone bill I hate.'),
(' I married Miss Right. I just didn’t know her first name was Always.'),
(' I pretend to work as long as they pretend to pay me.'),
(' I ran into my ex the other day, hit reverse, and ran into him again.'),
(' I ran three miles today. Finally I said, “Lady take your purse.”.'),
(' I read recipes the same way I read science fiction. I get to the end and I think, “Well, that’s not going to happen.”.'),
(' I said “no” to drugs, but they just wouldn’t listen.'),
(' I saw a woman wearing a sweat shirt with “Guess” on it…so I said “Implants?”.'),
(' I saw six men kicking and punching the mother-in-law. My neighbour said ‘Are you going to help?’ I said ‘No, six should be enough.’.'),
(' I should’ve known it wasn’t going to work out between my ex-wife and me. After all, I’m a Libra and she’s a bitch.'),
(' I sometimes go to my own little world, but that’s okay, they know me there.'),
(' I think, therefore I’m single.'),
(' I thought I wanted a career, turns out I just wanted paychecks.'),
(' I tried to hang myself with a bungee chord. I kept almost dying.'),
(' I used to be indecisive. Now I’m not sure.'),
(' I wanna hang a map of the world in my house. Then I’m gonna put pins into all the locations that I’ve traveled to. But first, I’m gonna have to travel to the top two corners of the map so it won’t fall down.'),
(' I want to die peacefully in my sleep, like my grandfather. Not screaming and yelling like the passengers in his car.'),
(' I was such an ugly kid. When I played in the sandbox the cat kept covering me up.'),
(' I was thinking about how people seem to read the Bible a whole lot more as they get older. Then it dawned on me… they were cramming for their finals.'),
(' I’d kill for a Nobel Peace Prize.'),
(' I’m a humble person, really. I’m actually much greater than I think I am.'),
(' I’m in shape. Round is a shape isn’t it.'),
(' I’m multi-talented: I can talk and piss you off at the same time.'),
(' I’ve learned that the people you care most about in life are taken from you too soon and all the less important ones just never go away.'),
(' If 4 out of 5 people SUFFER from diarrhea… does that mean that one enjoys it?'),
(' If a dog sniffs your ass, you’re probably a bitch.'),
(' If a leper gives you the finger, do you have to give it back?'),
(' If a mute kid swears does his mother wash his hands with soap?'),
(' If a turtle doesn’t have a shell, is he homeless or naked?'),
(' If at first you don’t succeed, skydiving is not for you!.'),
(' If Bill Gates had a penny for every time I had to reboot my computer…oh wait, he does.'),
(' If corn oil comes from corn, where does baby oil come from?'),
(' If everything seems to be coming your way, you’re probably in the wrong lane.'),
(' If God is watching us, the least we can do is be entertaining.'),
(' If good things come in small packages, then more good things can come in large packages.'),
(' If I agreed with you we’d both be wrong.'),
(' If I’d shot you sooner, I’d be out of jail by now.'),
(' If it’s true that we are here to help others, then what exactly are the others here for?'),
(' If life hands you lemons, break out the tequila!.'),
(' If sex is a pain in the ass, then you’re doing it wrong….'),
(' If the number 2 pencil is the most popular, why is it still number 2?'),
(' If Wal-Mart is lowering prices every day, why isn’t anything in the store is free yet?'),
(' If winning isn’t everything why do they keep score?'),
(' If you are supposed to learn from your mistakes, why do some people have more than one child.'),
(' If you can stay calm while all around you is chaos, then you probably haven’t completely understood the situation.'),
(' If you can’t convince them, confuse them.'),
(' If you do not say it, they can’t repeat it.'),
(' If you don’t care where you are, then you ain’t lost.'),
(' If you go to sleep with a itching ass you will wake up with a stinking finger ….'),
(' If you keep your feet firmly on the ground, you’ll have trouble putting on your pants.'),
(' If you must choose between two evils, pick the one you’ve never tried before.'),
(' If you think nobody cares if you’re alive, try missing a couple of payments.'),
(' If you’re going to ride my ass at least pull my hair and make me scream!.'),
(' If you’re looking for sympathy, you’ll find it in the dictionary between “shit” and “syphilis”.'),
(' If your dog is barking at the back door and your wife is yelling at the front door, who do you let in first? The dog, of course. He’ll shut up once you let him in.'),
(' Impotence: Nature’s way of saying “No hard feelings”.'),
(' Insanity is defined as doing the same thing over and over again, expecting different results.'),
(' Insanity is hereditary. You get it from your kids.'),
(' IRS: We’ve got what it takes to take what you’ve got.'),
(' Isn’t it odd the way everyone automatically assumes that the goo in soap dispensers is always soap? I like to fill mine with mustard, just to teach people a lesson in trust.'),
(' It ain’t the jeans that make your butt look fat.'),
(' It is hard to understand how a cemetery raised its burial cost and blamed it on the cost of living.'),
(' It matters not whether you win or lose: what matters is whether I win or lose.'),
(' It was love at first sight. Then I took a second look !!.'),
(' It’s amazing that the amount of news that happens in the world everyday always just exactly fits the newspaper.'),
(' It’s bad luck to be superstitious.'),
(' It’s not how good your work is, it’s how well you explain it.'),
(' It’s not the bullet that kills you, it’s the hole.'),
(' It’s not the fall that kills you; it’s the sudden stop at the end.'),
(' It’s so simple to be wise. Just think of something stupid to say and then don’t say it.'),
(' Jesus loves you, but everyone else thinks you’re an asshole.'),
(' Join The Army, visit exotic places, meet strange people, then kill them.'),
(' Just about the time when you think you can make ends meet, somebody moves the ends.'),
(' Just remember…if the world didn’t suck, we’d all fall off.'),
(' Keep the dream alive: Hit the snooze button.'),
(' Knowledge is knowing a tomato is a fruit; Wisdom is not putting it in a fruit salad.'),
(' Knowledge is power, and power corrupts. So study hard and be evil.'),
(' Laugh and the world laughs with you. Snore and you sleep alone.'),
(' Laugh at your problems, everybody else does.'),
(' Life’s a bitch, ’cause if it was a slut, it’d be easy.'),
(' Life’s like a bird, it’s pretty cute until it shits on your head.'),
(' Light travels faster than sound. This is why some people appear bright until you hear them speak.'),
(' Lite: the new way to spell “Light,” now with 20% fewer letters!.'),
(' Losing a husband can be hard: in my case it was almost impossible.'),
(' Married men live longer than single men, but they’re a lot more willing to die.'),
(' Materialism: buying things we don’t need with money we don’t have to impress people that don’t matter.'),
(' Men are like mascara, they usually run at the first sign of emotion.'),
(' Men have two emotions: Hungry and Horny. If you see him without an erection, make him a sandwich.'),
(' Money can’t buy happiness, but it sure makes misery easier to live with.'),
(' Money talks…but all mine ever says is good-bye.'),
(' Most women don’t know where to look when they’re eating a banana.'),
(' My drinking team has a bowling problem.'),
(' My mother never saw the irony in calling me a son-of-a-bitch.'),
(' My opinions may have changed, but not the fact that I am right.'),
(' My psychiatrist told me I was crazy and I said I want a second opinion. He said okay, you’re ugly too.'),
(' My wife ran off with my best friend last week. I miss him!.'),
(' Never agree to plastic surgery if the doctor’s office is full of portraits by Picasso.'),
(' Never get into fights with ugly people, they have nothing to lose.'),
(' Never hit a man with glasses. Hit him with a baseball bat.'),
(' Never test the depth of the water with both feet.'),
(' Never, under any circumstances, take a sleeping pill and a laxative on the same night.'),
(' No one is listening until you fart.'),
(' Nostalgia isn’t what it used to be.'),
(' One tequila, two tequila, three tequila, floor.'),
(' Only dead fish go with the flow.'),
(' Only in America… do banks leave both doors open and then chain the pens to the counters.'),
(' Panties not best thing on earth, but next to it.'),
(' People tend to make rules for others and exceptions for themselves.'),
(' Politicians and diapers have one thing in common. They should both be changed regularly, and for the same reason.'),
(' Politics is the art of looking for trouble, finding it, misdiagnosing it and then misapplying the wrong remedies.'),
(' Progress is made by lazy men looking for an easier way to do things.'),
(' Rap is to music as Etch-A-Sketch is to art.'),
(' Remember, if you smoke after sex you’re doing it too fast.'),
(' Roses are red violets are blue, I’m schizophrenic and so am I.'),
(' See, the problem is that God gives men a brain and a penis, and only enough blood to run one at a time.'),
(' Seen it all, done it all, can’t remember most of it.'),
(' Sex at age 90 is like trying to shoot pool with a rope.'),
(' Sex is not the answer. Sex is the question. “Yes” is the answer.'),
(' Sex on tv can’t hurt unless you fall off.'),
(' She said she was approaching forty, and I couldn’t help wondering from what direction.'),
(' Should crematoriums give discounts for burn victims?'),
(' Silence doesn’t mean your sexual performance left her speechless.'),
(' Smith & Wesson: The original point and click interface.'),
(' Some cause happiness wherever they go. Others whenever they go.'),
(' Some mistakes are too much fun to only make once.'),
(' Some of us learn from the mistakes of others; the rest of us have to be the others.'),
(' Some people are like Slinkies … not really good for anything, but you can’t help smiling when you see one tumble down the stairs.'),
(' Some people hear voices. Some see invisible people. Others have no imagination whatsoever.'),
(' Some people say “If you can’t beat them, join them”. I say “If you can’t beat them, beat them”, because they will be expecting you to join them, so you will have the element of surprise.'),
(' Sometimes the best helping hand you can give is a good, firm push.'),
(' Sometimes when I reflect back on all the beer I drink I feel shamed. Then I look into the glass and think about the workers in the brewery and all of their hopes and dreams. If I didn’t drink this beer, they might be out of work and their dreams would be shattered. Then I say to myself, “It is better that I drink this beer and let their dreams come true than be selfish and worry about my liver.'),
(' Squirrels – nature’s speed bumps.'),
(' Strangers have the best candy.'),
(' Stress is when you wake up screaming and you realize you haven’t fallen asleep yet.'),
(' The best thing about living at the beach is that you only have assholes on three sides of you.'),
(' The best way to lie is to tell the truth, carefully edited truth.'),
(' The big difference between sex for money and sex for free is that sex for money usually costs a lot less.'),
(' The big difference between sex for money and sex for free is that sex for money usually costs a lot less.'),
(' The difference between an oral thermometer and a rectal thermometer is in the taste.'),
(' The difference between divorce and legal separation is that a legal separation gives a husband time to hide his money.'),
(' The difference between fiction and reality? Fiction has to make sense.'),
(' The difference between in-laws and outlaws? Outlaws are wanted.'),
(' The early bird might get the worm, but the second mouse gets the cheese.'),
(' The easiest job in the world has to be coroner. Surgery on dead people. What’s the worst thing that could happen? If everything went wrong, maybe you’d get a pulse.'),
(' The farther away the future is, the better it looks.'),
(' The hardest thing to learn in life is which bridge to cross and which to burn.'),
(' The human brain is a wonderful thing. It starts working the moment you are born, and never stops until you stand up to speak in public.'),
(' The journey of a thousand miles begins with a broken fan belt and a flat tire.'),
(' The knack of flying is learning how to throw yourself at the ground and miss.'),
(' The last thing I want to do is hurt you. But it’s still on the list.'),
(' The last time I was inside a woman was when I went to the Statue of Liberty.'),
(' The last time someone listened to a Bush, a bunch of people wandered in the desert for 40 years!.'),
(' The main reason Santa is so jolly is because he knows where all the bad girls live.'),
(' The Miss Universe pageant is fixed. All the winners are from Earth.'),
(' The only difference between the people I’ve dated and Charles Manson is that Manson has the decency to look like a nut case when you first meet him.'),
(' The probability of someone watching you is proportional to the stupidity of your action.'),
(' The reason grandchildren and grandparents get along so well is because they have a common “enemy”.'),
(' The right to be heard does not automatically include the right to be taken seriously.'),
(' The sex was so good that even the neighbors had a cigarette.'),
(' The shinbone is a device for finding furniture in a dark room.'),
(' The sole purpose of a child’s middle name, is so he can tell when he’s really in trouble.'),
(' The trouble with being punctual is that nobody’s there to appreciate it.'),
(' The trouble with doing something right the first time is that nobody appreciates how difficult it was.'),
(' The voices in my head may not be real, but they have some good ideas!.'),
(' There are no winners in life…only survivors.'),
(' There are three kinds of people: The ones who learn by reading. The ones who learn by observation. And the rest of them who have to touch the fire to learn it’s hot.'),
(' There are two kinds of friends : those who are around when you need them, and those who are around when they need you.'),
(' There are two kinds of people who don’t say much: those who are quiet and those who talk a lot.'),
(' There’s a fine line between cuddling and holding someone down so they can’t get away.'),
(' They call it “pms” because “mad cow disease” was already taken.'),
(' They keep saying the right person will come along, I think mine got hit by a truck.'),
(' Think of how stupid the average person is, and realize half of them are stupider than that.'),
(' This isn’t an office. It’s hell with fluorescent lighting.'),
(' To be sure of hitting the target, shoot first and call whatever you hit the target.'),
(' To err is human, to blame it on somebody else shows management potential.'),
(' To steal ideas from one person is plagiarism. To steal from many is research.'),
(' True friendship comes when the silence between two people is comfortable.'),
(' Trust but verify.'),
(' Two antennas met on a roof, fell in love and got married. The ceremony wasn’t much, but the reception was excellent.'),
(' Two years ago I married a lovely young virgin, and if that doesn’t change soon, I’m gonna divorce her.'),
(' Unless you’re the lead dog, the view never changes.'),
(' Vegetarian: Native American definition for “lousy hunter”.'),
(' Virginity is like a soapbubble, one prick and it is gone.'),
(' War does not determine who is right – only who is left.'),
(' WARNING: The consumption of alcohol may cause you to think you can sing.'),
(' We are all part of the ultimate statistic – ten out of ten die.'),
(' We are all time travelers moving at the speed of exactly 60 minutes per hour.'),
(' We are all time travelers moving at the speed of exactly 60 minutes per hour.'),
(' We have all heard that a million monkeys banging on a million typewriters will eventually reproduce the entire works of Shakespeare. Now, thanks to the Internet, we know this is not true.'),
(' We have enough gun control. What we need is idiot control.'),
(' We live in a society where pizza gets to your house before the police.'),
(' We never really grow up, we only learn how to act in public.'),
(' Well aren’t you a waste of two billion years of evolution.'),
(' What has four legs and an arm? A happy pit bull.'),
(' What if there were no hypothetical questions?'),
(' What is the most important thing to learn in chemistry?'),
(' What’s the difference between a northern fairytale and a southern fairytale? A northern fairytale begins “Once upon a time…” A southern fairytale begins “Y’all ain’t gonna believe this shit…”.'),
(' When in doubt, mumble.'),
(' When tempted to fight fire with fire, remember that the Fire Department usually uses water.'),
(' When we were together, you always said you’d die for me. Now that we’ve broke up, I think it’s time you kept your promise!.'),
(' When you choke a smurf, what color does it turn?'),
(' When you go into court, you are putting your fate into the hands of people who weren’t smart enough to get out of jury duty.'),
(' When you go to the drugstore, why are the condoms not in with the other party supplies?'),
(' When you stop believing in Santa Claus is when you start getting clothes for Christmas!.'),
(' Whenever I fill out an application, in the part that says “If an emergency, notify:” I put “DOCTOR”. What’s my mother going to do?'),
(' Who invented the brush they put next to the toilet? That thing hurts!.'),
(' Who lit the fuse on your tampon?'),
(' Who was the first to see a cow and think “I wonder what will happen if I squeeze these dangly things and drink whatever comes out?”.'),
(' Whoever coined the phrase “Quiet as a mouse” has never stepped on one.'),
(' Why didn’t Noah swat those two mosquitoes?'),
(' Why do Americans choose from just two people to run for president and 50 for Miss America?'),
(' Why do people keep running over a string a dozen times with their vacuum cleaner, then reach down, pick it up, examine it, then put it down to give their vacuum one more chance?'),
(' Why do they lock gas station bathrooms? Are they afraid someone will clean them?'),
(' Why do they use sterilized needles for death by lethal injection?'),
(' Why do we press harder on a remote control when we know the batteries are getting weak?'),
(' Why do women always ask questions that have no right answers?'),
(' Why do you need a driver’s license to buy liquor when you can’t drink and drive?'),
(' Why does someone believe you when you say there are four billion stars, but check when you say the paint is wet?'),
(' Why don’t you slip into something more comfortable…like a coma.'),
(' Why is a bra singular and panties plural?'),
(' Why is it called Alcoholics ANONYMOUS when the first thing you do is stand up and say, ‘My name is Peter and I am an alcoholic’.'),
(' Why is it called tourist season if we can’t shoot them?'),
(' Why is it so hard for women to find men that are sensitive, caring, and good-looking? Because those men already have boyfriends.'),
(' Why is it that in the US: If you take off all your clothes and walk down the street waving a machete and firing an Uzi, terrified citizens will phone the police and report: “There’s a naked person outside!”.'),
(' Why is it that most nudists are people you don’t want to see naked?'),
(' Wise people think all they say, fools say all they think.'),
(' With a calendar, your days are numbered.'),
(' With sufficient thrust, pigs fly just fine.'),
(' Without ME, it’s just AWESO.'),
(' Without nipples, breasts would be pointless.'),
(' Women may not hit harder, but they hit lower.'),
(' Women might be able to fake orgasms. But men can fake a whole relationship.'),
(' Women should not have children after 35. Really… 35 children are enough.'),
(' Women will never be equal to men until they can walk down the street with a bald head and a beer gut, and still think they are sexy.'),
(' Worrying works! 90% of the things I worry about never happen.'),
(' You are depriving some poor village of its idiot.'),
(' You are such a good friend that if we were on a sinking ship together and there was only one life jacket… I’d miss you heaps and think of you often.'),
(' You can easily judge the character of a man by how he treats those who can do nothing for him.'),
(' You do not need a parachute to skydive. You only need a parachute to skydive twice.'),
(' You ever make fun of someone so much, you think you should thank them for all the good times you’ve had?'),
(' You have two choices in life: You can stay single and be miserable, or get married and wish you were dead.'),
(' You know the world is going crazy when the best rapper is a white guy, the best golfer is a black guy, the tallest guy in the NBA is Chinese, the Swiss hold the America’s Cup, France is accusing the U.S. of arrogance, Germany doesn’t want to go to war, and the three most powerful men in America are named ‘Bush’, ‘Dick’, and ‘Colon’. Need I say more?'),
(' You know your children are growing up when they stop asking you where they came from and refuse to tell you where they’re going.'),
(' You know, they got a luggage store in the airport? A place to buy a piece of luggage? How late do you have to be for a flight where you’re like, ‘Fuck it – just grab a pile of shit. We’ll get a bag at the airport’.'),
(' You may have a heart of gold, but so does a hard-boiled egg.'),
(' You’re never too old to learn something stupid.'),
(' Your gene pool could use a little chlorine.'),
(' Your kid may be an honors student, but you’re still an idiot.')